import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import AuthProvider from './components/AuthProvider'
import backgroundImage from './assets/background.jpg';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'SH WEB SWITCH',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <main style={{ backgroundImage: `url(${backgroundImage.src})` }} className="bg-center bg-cover min-h-screen text-white">
            <div className="min-h-screen backdrop-blur-xl">
              <div className="mx-auto p-4 container">
                <p className="text-4xl lg:text-5xl font-semibold">
                  <span className="text-blue-600">SH</span> WEB SWITCH
                </p>
                <p>Control every application made by SH MARUF</p>
                {children}
              </div>
            </div>
          </main>
        </AuthProvider>
      </body>
    </html>
  )
}
